# alacritty.toml

live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "windowed"
title = "pwd"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[scrolling]
history = 99999

# program="/bin/bash"
[shell]
program="/bin/zsh"

[font]
builtin_box_drawing = false
size = 6

# [font.bold]
# family = "FantasqueSansMNerdFont Mono"
# style  = "Bold"

# [font.bold_italic]
# family = "FantasqueSansMNerdFont Mono"
# style  = "Bold Italic"

# [font.glyph_offset]
# x = 0
# y = 0

# [font.italic]
# family = "FantasqueSansMNerdFont Mono"
# style  = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

# [colors.primary]
# background = "#232323"
# foreground = "#C0C5CE"

# [colors.bright]
# black = "#5C5C5C"
# blue = "#6699CC"
# cyan = "#5FB3B3"
# green = "#A6BC99"
# magenta = "#824F82"
# red = "#E57373"
# white = "#F3F4F5"
# yellow = "#FAC863"

# [colors.cursor]
# cursor = "CellForeground"
# text = "CellBackground"

# [colors.footer_bar]
# background = "#C0C5CE"
# foreground = "#232323"

# [colors.hints.end]
# background = "CellBackground"
# foreground = "CellForeground"

# [colors.hints.start]
# background = "CellBackground"
# foreground = "CellForeground"

# [colors.line_indicator]
# background = "None"
# foreground = "None"

# [colors.normal]
# black = "#232323"
# blue = "#6699CC"
# cyan = "#5FB3B3"
# green = "#A6BC99"
# magenta = "#824F82"
# red = "#E57373"
# white = "#C0C5CE"
# yellow = "#FAC863"

# [colors.search.focused_match]
# background = "CellBackground"
# foreground = "CellForeground"

# [colors.search.matches]
# background = "CellBackground"
# foreground = "CellForeground"

# [colors.selection]
# background = "CellForeground"
# text = "CellBackground"

# [colors.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"

[bell]
animation = "EaseOutExpo"
color = "#C0C5CE"
command = "None"
duration = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
unfocused_hollow = true
vi_mode_style = "None"
style = { shape = "Beam" }
blink_interval = 50

# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mods = "Control|Shift"

# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control|Shift"

# [[keyboard.bindings]]
# action = "ScrollPageUp"
# key = "PageUp"
# mods = "Shift"

# [[keyboard.bindings]]
# action = "ScrollPageDown"
# key = "PageDown"
# mods = "Shift"

# [[keyboard.bindings]]
# action = "ScrollToTop"
# key = "Home"
# mods = "Shift"

# [[keyboard.bindings]]
# action = "ScrollToBottom"
# key = "End"
# mods = "Shift"

# [mouse]
# hide_when_typing = true

[debug]
highlight_damage = false
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

